# -*- coding: utf-8 -*-
"""Traffic_GeekTrust_challenge.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AURDPQ9gHPbntlfEfWCB5zqLluK3DgnS
"""

#Getter Function to get Input
def getter(input_file):
    fo=open(input_file,'r')
    i=fo.read()
    i=i.split(" ")
    w=str(i[0])
    o_1=int(i[1])
    o_2=int(i[2])
    return w,o_1,o_2
#or 
def getter_1():
  i=input("Enter the input in this format (Weather orbit1_speed orbit2_speed: ")
  i=i.split(" ")
  w=str(i[0])
  o_1=int(i[1])
  o_2=int(i[2])
  return w,o_1,o_2

#Function For Sunny Weather

def sunny(b,c):
    o1=[18,20]
    o2=[20,10]
    bi=[10,2]
    tu=[12,1]
    ca=[20,3]
    o1[1],o2[1]=int(o1[1]-(o1[1]*(10/100))),int(o2[1]-(o2[1]*(10/100)))
    
    def bike(b,c,o1,o2,bi):
        if b<bi[0]:
            x=b
            to1=(((60*o1[0])/x)+(o1[1]*bi[1]))
            
        else:
            to1=(((60*o1[0])/bi[0])+(o1[1]*bi[1]))
        if c<bi[0]:
             y=c
             to2=((60*o2[0])/y)+(o2[1]*bi[1])
        else:
            to2=((60*o2[0])/bi[0])+(o2[1]*bi[1])
        
        if to1<to2:
            return ('o1 {}'.format(to1))
        else:
            return ('o2 {}'.format(to2))
    
    def tuktuk(b,c,o1,o2,tu):
        if b<tu[0]:
            x=b
            to1=((60*o1[0])/x)+(o1[1]*tu[1])
        else:
            to1=((60*o1[0])/tu[0])+(o1[1]*tu[1])
        if c<tu[0]:
             y=c
             to2=((60*o2[0])/y)+(o2[1]*tu[1])
        else:
            to2=((60*o2[0])/tu[0])+(o2[1]*tu[1])
        
        if to1<to2:
            return ('o1 {}'.format(to1))
        else:
            return ('o2 {}'.format(to2))
    def car(b,c,o1,o2,ca):
        if b<ca[0]:
            x=b
            to1=((60*o1[0])/x)+(o1[1]*ca[1])
        else:
            to1=((60*o1[0])/ca[0])+(o1[1]*ca[1])
        if c<ca[0]:
             y=c
             to2=((60*o2[0])/y)+(o2[1]*ca[1])
        else:
            to2=((60*o2[0])/ca[0])+(o2[1]*ca[1])
            
        if to1<to2:
            return ('o1 {}'.format(to1))
        else:
            return ('o2 {}'.format(to2))
        
    s=bike(b,c,o1,o2,bi)
    r=tuktuk(b,c,o1,o2,tu)
    t=car(b,c,o1,o2,ca)
    
    
    
    s=s.split()
    r=r.split()
    t=t.split()
    
    def less(s,r,t):
        if(float(s[1])<=float(r[1]) and float(s[1])<=float(t[1])):
            if s[0]=='o1':
                print('Bike Orbit1')
            else:
                print('Bike Orbit2')
        elif(float(r[1])<=float(s[1]) and float(r[1])<=float(t[1])):
            if r[0]=='o1':
                print('Tuktuk Orbit1')
            else:
                print('Tuktuk Orbit2')
                
        elif(float(t[1])<=float(s[1]) and float(t[1])<=float(r[1])):
            if t[0]=='o1':
                print('Car Orbit1')
            else:
                print('Car Orbit2')
        
            
    less(s, r, t)

#Function For Rainy Weather

def rainy(b,c):
    o1=[18,20]
    o2=[20,10]
    tu=[12,1]
    ca=[20,3]
    o1[1],o2[1]=int(o1[1]+(o1[1]*0.2)),int(o2[1]+(o2[1]*0.2))

    def tuktuk(b,c,o1,o2,tu):
        if b<tu[0]:
            x=b
            to1=((60*o1[0])/x)+(o1[1]*tu[1])
        else:
            to1=((60*o1[0])/tu[0])+(o1[1]*tu[1])
        if c<tu[0]:
             y=c
             to2=((60*o2[0])/y)+(o2[1]*tu[1])
        else:
            to2=((60*o2[0])/tu[0])+(o2[1]*tu[1])
        

        if to1<to2:
            return ('o1 {}'.format(to1))
        else:
            return ('o2 {}'.format(to2))
    def car(b,c,o1,o2,ca):
        if b<ca[0]:
            x=b
            to1=((60*o1[0])/x)+(o1[1]*ca[1])
        else:
            to1=((60*o1[0])/ca[0])+(o1[1]*ca[1])
        if c<ca[0]:
             y=c
             to2=((60*o2[0])/y)+(o2[1]*ca[1])
        else:
            to2=((60*o2[0])/ca[0])+(o2[1]*ca[1])
        
        if to1<to2:
            return ('o1 {}'.format(to1))
        else:
            return ('o2 {}'.format(to2))
        
    r=tuktuk(b,c,o1,o2,tu)
    t=car(b,c,o1,o2,ca)
    
    
    r=r.split()
    t=t.split()
    
    
    
    def less(r,t):
        
        if(float(r[1])<=float(t[1])):
            if r[0]=='o1':
                print('Tuktuk Orbit1')
            else:
                print('Tuktuk Orbit2')
                
        elif(float(t[1])<float(r[1])):
            if t[0]=='o1':
                print('Car Orbit1')
            else:
                print('Car Orbit2')
    less(r, t)

#Function For Windy Weather

def windy(b,c):
    o1=[18,20]
    o2=[20,10]
    bi=[10,2]
    tu=[12,1]
    ca=[20,3]
    
    def bike(b,c,o1,o2,bi):
        if b<bi[0]:
            x=b
            to1=((60*o1[0])/x)+(o1[1]*bi[1])
        else:
            to1=((60*o1[0])/bi[0])+(o1[1]*bi[1])
        if c<bi[0]:
             y=c
             to2=((60*o2[0])/y)+(o2[1]*bi[1])
        else:
            to2=((60*o2[0])/bi[0])+(o2[1]*bi[1])
        

        if to1<to2:
            return ('o1 {}'.format(to1))
        else:
            return ('o2 {}'.format(to2))
    
    def tuktuk(b,c,o1,o2,tu):
        if b<tu[0]:
            x=b
            to1=((60*o1[0])/x)+(o1[1]*tu[1])
        to1=((60*o1[0])/tu[0])+(o1[1]*tu[1])
        if c<tu[0]:
             y=c
             to2=((60*o2[0])/y)+(o2[1]*tu[1])
        else:
            to2=((60*o2[0])/tu[0])+(o2[1]*tu[1])
        
        
        if to1<to2:
            return ('o1 {}'.format(to1))
        else:
            return ('o2 {}'.format(to2))
    def car(b,c,o1,o2,ca):
        if b<ca[0]:
            x=b
            to1=((60*o1[0])/x)+(o1[1]*ca[1])
        else:
            to1=((60*o1[0])/ca[0])+(o1[1]*ca[1])
        if c<ca[0]:
             y=c
             to2=((60*o2[0])/y)+(o2[1]*ca[1])
        else:
            to2=((60*o2[0])/ca[0])+(o2[1]*ca[1])
        
        if to1<to2:
            return ('o1 {}'.format(to1))
        else:
            return ('o2 {}'.format(to2))
        
    s=bike(b,c,o1,o2,bi)
    r=tuktuk(b,c,o1,o2,tu)
    t=car(b,c,o1,o2,ca)
    
    s=s.split()
    r=r.split()
    t=t.split()
    
    def less(s,r,t):
        if(float(s[1])<=float(r[1]) and float(s[1])<=float(t[1])):
            if s[0]=='o1':
                print('Bike Orbit1')
            else:
                print('Bike Orbit2')
        elif(float(r[1])<=float(s[1]) and float(r[1])<=float(t[1])):
            if r[0]=='o1':
                print('Tuktuk Orbit1')
            else:
                print('Tuktuk Orbit2')
                
        elif(float(t[1])<float(s[1]) and float(t[1])<float(r[1])):
            if t[0]=='o1':
                print('Car Orbit1')
            else:
                print('Car Orbit2')
    less(s, r, t)

#Calling functions in Main functions

#input_file = path
#a,b,c=getter(input_file)
a,b,c=getter_1()
if a=='sunny'or a=='Sunny':
  sunny(b,c)
elif a=='rainy'or a=='Rainy':
  rainy(b,c)
elif a=='windy'or a=='Windy':
  windy(b,c)
